---
title: "Curriculum Vitae"
author: "FirstName LastName"
date: "`r format(Sys.time(), '%B %Y')`"

web: www.Website.org
github: mygithub
twitter: myTwitter
phone: "(352) 555-5555"
email: email@ufl.edu

updated: yes

header-includes:
- \usepackage{etaremune} # for reverse-numbered list of publications etc
# see https://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/etaremune/etaremune.pdf
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
- \fancyfoot[R]{`r format(Sys.time(), '%B %Y')`} # month & year on footer right
- \fancyhead[R]{FirstName LastName, p. \thepage} # name and page on header right
- \fancyhead[L]{ } # name and page on header left
- \usepackage{setspace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
  # to center to top level (#) headings (my name) and change color of font
  # more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# centersub-headings (##) & sub-sub-headings (###) & change font color
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \usepackage{sectsty} \subsubsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
- \usepackage{xhfill} # modification of line color and width

geometry: margin=1in
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
fontawesome: yes

output:
  pdf_document: default
  # html_document: null
  df_print: paged
  toc: no
  # word_document: default
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
# library(gridExtra)
# library(kableExtra)
# library(citr)
# library(RefManageR)
```
<!-- \begin{document}. -->

<!-- this next line suppresses the header (line, name,  page number) on 1st page -->
\thispagestyle{empty}  

# Your Name
\vspace{-0.3cm}  <!--space between name and address -->
<!--\hfill moves all way to right -->
University of Florida\hfill email@ufl.edu  
Dept. of Metaphysics\hfill +1 (352) 867-5309  
PO Box 110430\hfill&nbsp;[www.your-web-site.org](www.your-web-site.org)  
Gainesville, FL 32611-1234 USA\hfill&nbsp;[\@YouTwitterOrGithub](https://twitter.com/you) 
\vspace{-0.5cm}  <!--there was too much space, so reduced it with minus: -Xcm -->

\par\noindent\rule{\textwidth}{0.4pt} <!-- makes the line   -->


\vspace{-0.6cm}  

<!-- ------------------------------------- -->

### Education
<!--to indent a block of stuff treat it as a 'group' and then set leftskip -->
<!--be sure to indicate where the group ends with \endgroup -->

\begingroup 
\setlength{\leftskip}{.2cm} 

<!-- ### EDUCATION \hrulefill\ -->

<!-- TEXT \hrulefill\ -->
<!-- Here is some text\xfill{1pt} \par -->
<!-- Here is some text\xfill{8pt} \par -->
<!-- Here is some text\xhrulefill{darkmidnightblue}{2pt}\par -->
<!-- Here is some text\xhrulefill{darkmidnightblue}{1ex}\par -->
<!-- HOW TO MAKE LINE COLOR SAME'? -->
<!-- https://tex.stackexchange.com/questions/32597/vertically-centered-horizontal-rule-filling-the-rest-of-a-line -->
<!-- \textbf{\textcolor{darkmidnightblue}{EDUCATION }}\xrfill[0.5ex]{0.5pt} -->

<!-- ### EDUCATION \hrulefill -->

2001\hspace{4mm} Ph.D. in Biology, University of Mars  
<!-- &nbsp;&nbsp;&nbsp;&nbsp;\hspace{6mm}  _Dissertation Advisor: Person Name_   -->
1995\hspace{4mm} M.S. in Biology, University of Venus  
<!-- &nbsp;&nbsp;&nbsp;&nbsp;\hspace{6mm} _Thesis Advisor: Person Name_   -->
1994\hspace{4mm} B.S. in Evolution, University of California 

\endgroup 

<!-- ------------------------------------- -->

### Professional Appointments

\begingroup 
\setlength{\leftskip}{.2cm} 

2020-Present\hspace{6mm}**Professor**, University of California  
&nbsp;\hspace{24mm}Department of Wildlife Ecology

2018-2020\hspace{10mm}**President**, Student Group 

2017-2018\hspace{10mm}**Treasurer**, Student Group

\endgroup

<!-- ------------------------------------- -->

\vspace{-0.2cm}
### Fellowships

\begingroup 
\setlength{\leftskip}{.2cm} 

2022\hspace{4mm}Graduate Fellowship, University of Florida  
2020\hspace{4mm}Best Poster Presentation, Ecological Society of Mexico  
2020\hspace{4mm}Outstanding Teaching Assistant, College of Science, Univ. of Florida

\endgroup

<!-- ------------------------------------- -->

### Grants

\begingroup 
\setlength{\leftskip}{.2cm}  

1. MH Foundaiton. 'Support for the Study of bugs' ($100,000, 2022-2023)

1. MNGA Foundation. 'Bugs are great' ($74,060, 2020-2021)

\endgroup

<!-- ------------------------------------- -->

### Publications 

1. Wang, Q., Chen, W., & Liang, Y. (2017). Effects of inquiry-based learning supported by mobile technology on students’ learning achievements and attitudes. Journal of Educational Technology Development and Exchange, 8(1), 1-20. 

1. Wong, L. H., Chai, C. S., & Tan, E. (2016). Virtual laboratories in science education: A review of the literature. Journal of Educational Technology Development and Exchange, 9(1), 1-19. 

1. Squire, K. (2011). Video games and learning: Teaching and participatory culture in the digital age. Teachers College Press. 

<!-- IF YOU WANT REVERSE NUMBERING -->

<!-- \begin{etaremune} -->

<!-- \item -->
<!-- Wang, Q., Chen, W., & Liang, Y. (2017). Effects of inquiry-based learning supported by mobile technology on students’ learning achievements and attitudes. \textit{\textbf{Journal of Educational Technology Development and Exchange}}, 8(1), 1-20.  -->

<!-- \item -->
<!-- Wong, L. H., Chai, C. S., & Tan, E. (2016). Virtual laboratories in science education: A review of the literature. \textit{\textbf{Journal of Educational Technology Development and Exchange}}, 9(1), 1-19.  -->

<!-- \item -->
<!-- Squire, K. (2011). Video games and learning: Teaching and participatory culture in the digital age. Teachers College Press. -->

<!-- \end{etaremune} -->


<!-- ------------------------------------- -->

<!-- ### Manuscripts in Preparation  -->

### Teaching Experience
\begingroup 
\setlength{\leftskip}{.2cm}  

Guest Lecture, The Future of Rain Forests (Undergraduate, 2022)  
Instructor, Data Collection & Field Methods (Graduate, 2019)  

\endgroup 



<!-- ------------------------------------- -->



### Student Advising


<!-- ------------------------------------- -->


### Service

\begingroup 
\setlength{\leftskip}{.2cm}

Search Committee, UF QUEST Program (2023)  
Samuel P. Harn Museum of Art Faculty Council (2012-2015)   
Selection Committee, UF Undergraduate Faculty Mentor/Advisor of the Year (2022)    


<!-- ------------------------------------- -->


### Referee for journals (No. of reviews)
\setlength{\leftskip}{.2cm}  

*Trends in Ecology and Evolution* (1)   
*Nature Human Behavior* (1)  
*Nature Ecology & Evolution* (2)  

\endgroup 


<!-- ------------------------------------- -->


### Presentations 

<!-- Invited, submitted, posters -->

<!-- ------------------------------------- -->


### Extension / Outreach Activities


<!-- ------------------------------------- -->
<!-- OTHER CATEGORIES --->

<!-- ### Professional service -->
<!-- ### Professional memberships -->
<!-- ### Professional Development/Training -->
<!-- ### Technical Skills   -->
<!-- ### Language Skills   -->
<!-- ### Presentations   -->
<!-- ### 'Named' Scholarships & Fellowships   -->
<!-- ### Certifications & Licenses   -->
<!-- ### Foreign Study   -->
<!-- ### International Experience   -->
<!-- ### Programming Skills   -->
<!-- ### Reviewer for Journals   -->
<!-- ### Editorial Boards   -->
<!-- ### Exhibits   -->
<!-- ### Organizing events -->
<!-- ### Internships   -->
<!-- ### Administrative Experience   -->
<!-- ### Supervisory Experience   -->
<!-- ### Consulting Experience   -->
<!-- ### Advising   -->
<!-- ### Outreach   -->
<!-- ### Advisory Committees   -->
<!-- ### Guest Lectures in Courses -->  
<!-- ### Language Skills -->  
<!-- ### Patents   -->
