---
title: 'Student Learning Objectives'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
web: www.BrunaLab.org
github: embruna
twitter: https://twitter.com/BrunaLab
phone: (352) 514-3935
email: embruna@ufl.edu
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
site: bookdown::bookdown_site
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Syllabus, p. \thepage}
- \fancyhead[L]{IDS 2935 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
# - \usepackage{sectsty} \allsectionsfont{\raggedright}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
output: pdf_document
# output: 
#   pdf_document:
#     fig_caption: yes   
# classoption: 
#   landscape
---


```{r setupslo1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# library(gridExtra)
library(kableExtra)
# library(egg)
# library(magick)
# library(citr)
```



### DOCTORAL STUDENT COMMITTEE SERVICE, UNIVERSITY OF FLORIDA

```{r DocCmte, echo=FALSE,message = FALSE,warning=FALSE}
grad_advised<-read_csv("./cv_rmd_template/cv_sections/cv_files/grad_advised.csv") %>% filter(role=="doc_cmte") %>% select(-role)
kbl(grad_advised,digits = 1,
                  format = "latex",
                  align="l",
                  col.names = NULL,
                  row.names = FALSE,
                  booktabs=T,
                  longtable = T, 
                  linesep = "") %>%
  kable_styling(bootstrap_options = c("hover"),
                latex_options = c("scale_down"),
                full_width = F,
                font_size = 10,
                position = "left") %>%
  sub("\\\\toprule", "", .) %>%
  sub("\\\\bottomrule", "", .)
```