---
title: "Curriculum Vitae"
# title: "&nbsp;"
author: "Emilio M. Bruna"
# email: embruna@ufl.edu
# web: www.BrunaLab.org
# github: embruna
# twitter: BrunaLab
# phone: "(352) 514-3935"
# date: "`r format(Sys.time(), '%B %Y')`"
# geometry: margin=1in
# linkcolor: blue
# urlcolor: blue
# tables: true
# jobtitle: "Professor & Distinguished Teaching Scholar, University of Florida"
# address: "PO Box 110430 · 110 Newins-Ziegler Hall · Gainesville, FL 32611-040"
# fontawesome: yes
# # bibliography: BrunaPublications.bib
# # bibliography: BrunaPublications.bib
# # bibliography_software: chapters.bib
# # csl: biotropica.csl
# csl: brunacv2.csl
# updated: yes
# site: bookdown::bookdown_site
# header-includes:
# - \usepackage{etaremune} #for reverse-numbered list
# - \usepackage[default]{sourcesanspro}
# - \usepackage{fancyhdr}
# - \pagestyle{fancy}
# - \fancyfoot{}
# - \fancyfoot[R]{`r format(Sys.time(), '%B %Y')`}
# - \fancyhead[R]{Emilio M. Bruna, p. \thepage}
# - \usepackage{setspace}
# - \usepackage{parskip} 
# - \usepackage{xcolor} 
# - \AtBeginDocument{\let\maketitle\relax} # this removes default title section
#   # to center to top level (#) headings - my name 
#   # more info # https://www.ctan.org/pkg/sectsty
# - \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# - \usepackage{sectsty} \subsubsectionfont{\color{darkmidnightblue}}
# # http://latexcolor.com/ to choose colors
# - \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
# - \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# # - \setstretch{1.0}
# # https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

output: 
  pdf_document:
    toc: yes 
   
   
---
## REFS

```{r child = 'pubs.Rmd'}
```


more text 

## REFS2

```{r child = 'chapters.Rmd'}
```

